eight_points_guzzle:
    clients:
        bitrise_client:
            # Write here the host where to do requests
            base_url: "https://api.bitrise.io/v0.1/"

            options:
                timeout: 30

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    Authorization: "token %env(API_KEY)%"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin:
